# Generated by Django 3.2.4 on 2021-06-14 06:57

from django.db import migrations, models
import django.db.models.deletion
import offers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now_add=True)),
                ('date_deadline', models.DateTimeField(default=offers.models.two_more_days)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('price_offer', models.IntegerField()),
                ('duration', models.TimeField()),
                ('was_taken', models.BooleanField(default=False)),
                ('field', models.ManyToManyField(to='offers.Skills')),
                ('offer_maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
        ),
    ]
