# Generated by Django 3.2.4 on 2021-06-14 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='was_taken',
            new_name='expired',
        ),
    ]
