# Generated by Django 3.2.4 on 2021-06-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_rename_was_taken_offers_expired'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='expired',
            new_name='completed',
        ),
    ]
