# Generated by Django 3.2.4 on 2021-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_rename_expired_offers_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
