# Generated by Django 3.2.4 on 2021-06-15 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offers_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='completed',
            new_name='accepted',
        ),
    ]
