# Generated by Django 3.2.4 on 2021-06-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_completed_offers_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='price_offer',
        ),
    ]
