# Generated by Django 3.2.4 on 2021-06-17 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210617_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 14, 23, 37, 460576)),
        ),
    ]
