# Generated by Django 3.2.4 on 2021-06-18 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_rename_completed_offers_accepted'),
        ('main', '0017_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 0, 30, 26, 435529)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(null=True, to='offers.Skills'),
        ),
    ]
