# Generated by Django 3.2.4 on 2021-06-20 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_profile_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reviews_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 11, 3, 56, 169969)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 - Horrible'), (2, '2 - just an amateur'), (3, '3 - Can get better'), (4, '4 - nah..'), (5, '5 - average at best'), (5, '6 - OK'), (5, '7 - kinda fine'), (5, '8 - Really good'), (5, '9 - Super great'), (5, '10 - A God at his profession')]),
        ),
    ]
