# Generated by Django 3.2.4 on 2021-06-20 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 55, 0, 979468)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, '1 - Horrible'), (2, '2 - just an amateur'), (3, '3 - Can get better'), (4, '4 - nah..'), (5, '5 - average at best'), (6, '6 - OK'), (7, '7 - kinda fine'), (8, '8 - Really good'), (9, '9 - Super great'), (10, '10 - A God')]),
        ),
    ]
