# Generated by Django 3.2.4 on 2021-06-20 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210620_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='approved',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 19, 1, 0, 907033)),
        ),
    ]
