# Generated by Django 3.2.4 on 2021-06-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
