# Generated by Django 3.2.4 on 2021-06-15 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0002_acceptoffer_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_date',
            field=models.DateField(default=datetime.date(2021, 6, 15)),
        ),
    ]
