# Generated by Django 3.2.4 on 2021-06-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0003_alter_acceptoffer_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptoffer',
            name='google_meet',
            field=models.URLField(default='http://meet.google.com/new'),
        ),
    ]
