# Generated by Django 3.2.4 on 2021-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0004_acceptoffer_google_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptoffer',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
