# Generated by Django 3.2.4 on 2021-06-16 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0005_acceptoffer_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptoffer',
            name='meeting_date',
        ),
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 10, 59, 7, 476434)),
        ),
    ]
