# Generated by Django 3.2.4 on 2021-06-16 10:57

import datetime
from django.db import migrations, models
import pros.models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0006_auto_20210616_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptoffer',
            name='code',
            field=models.CharField(default=pros.models.gen_code, max_length=500),
        ),
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 13, 57, 49, 860733)),
        ),
    ]
