# Generated by Django 3.2.4 on 2021-06-16 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0007_auto_20210616_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptoffer',
            name='google_meet',
        ),
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 14, 46, 55, 923779)),
        ),
    ]
