# Generated by Django 3.2.4 on 2021-06-17 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0008_auto_20210616_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 10, 44, 4, 928238)),
        ),
    ]
