# Generated by Django 3.2.4 on 2021-06-17 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0022_alter_acceptoffer_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 16, 57, 20, 65252)),
        ),
    ]
