# Generated by Django 3.2.4 on 2021-06-20 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0027_auto_20210620_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 11, 3, 56, 171018)),
        ),
    ]
