# Generated by Django 3.2.4 on 2021-06-20 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0029_alter_acceptoffer_meeting_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptoffer',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 55, 0, 983427)),
        ),
    ]
