# Generated by Django 3.2.4 on 2021-06-20 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0030_auto_20210620_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acceptoffer',
            name='approved',
        ),
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 18, 56, 12, 194591)),
        ),
    ]
