# Generated by Django 3.2.4 on 2021-06-20 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0031_auto_20210620_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptoffer',
            name='meeting_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 19, 1, 0, 911022)),
        ),
    ]
